images_dir: '/home/hbm22/Pictures/hmmetria'
  #images_dir: '/home/hbm22/Pictures/Experiments/flower'
dest_dir: '/home/hbm22/Experiments/25_03_25/Teste/'
  #dest_dir: '/home/hbm22/Experiments/11_11_2024/amostras'
