images_dir: '/home/hbm22/Pictures/hmmetria'
  #images_dir: '/home/hbm22/Pictures/Experiments/flower'
dest_dir: '/home/hbm22/Experiments/16_01_2025'
  #dest_dir: '/home/hbm22/Experiments/11_11_2024/amostras'
